// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/admin_pwd_login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authController"
                ],
                "summary": "管理端密码登录",
                "operationId": "adminPwdLogin",
                "parameters": [
                    {
                        "description": "密码登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PwdLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_SystemUserVo"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authController"
                ],
                "summary": "用户退出登录",
                "operationId": "userLogout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/auth/pwd_login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authController"
                ],
                "summary": "用户端密码登录",
                "operationId": "userPwdLogin",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/domain/add": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemDomainController"
                ],
                "summary": "添加域",
                "operationId": "addSystemDomain",
                "parameters": [
                    {
                        "description": "添加域请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddDomainRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-bool"
                        }
                    }
                }
            }
        },
        "/domain/get_page": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemDomainController"
                ],
                "summary": "获取域的页数据",
                "operationId": "getDomainInfoPage",
                "parameters": [
                    {
                        "description": "获取域的页数据请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SystemDomainPageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_PageResult-schema_SystemDomain"
                        }
                    }
                }
            }
        },
        "/domain/list_domains": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemDomainController"
                ],
                "summary": "获取域列表",
                "operationId": "listDomains",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-array_schema_SystemDomain"
                        }
                    }
                }
            }
        },
        "/domain/remove": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemDomainController"
                ],
                "summary": "删除域信息",
                "operationId": "removeDomainInfo",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "域id",
                        "name": "domainId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-bool"
                        }
                    }
                }
            }
        },
        "/domain/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemDomainController"
                ],
                "summary": "更新域信息",
                "operationId": "updateDomainInfo",
                "parameters": [
                    {
                        "description": "更新域请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateDomainRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-bool"
                        }
                    }
                }
            }
        },
        "/init/check": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "initController"
                ],
                "summary": "查看是否需要初始化",
                "operationId": "checkNeedInit",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_CheckResult"
                        }
                    }
                }
            }
        },
        "/init/init_project": {
            "post": {
                "description": "当配置文件的数据库配置为空时，需要进行项目初始化",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "initController"
                ],
                "summary": "项目初始化",
                "operationId": "initProject",
                "parameters": [
                    {
                        "description": "初始化相关参数",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.InitProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-any"
                        }
                    }
                }
            }
        },
        "/init/test_db_connection": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "initController"
                ],
                "summary": "测试数据库是否能够连接",
                "operationId": "testDBConnection",
                "parameters": [
                    {
                        "description": "测试数据库连接相关参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DBConnectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_CheckResult"
                        }
                    }
                }
            }
        },
        "/user/add": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemUserController"
                ],
                "summary": "添加用户信息",
                "operationId": "addSystemUser",
                "parameters": [
                    {
                        "description": "添加用户请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddSystemUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-bool"
                        }
                    }
                }
            }
        },
        "/user/get_info": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemUserController"
                ],
                "summary": "获取登录用户信息",
                "operationId": "getUserInfo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_SystemUserVo"
                        }
                    }
                }
            }
        },
        "/user/get_page": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemUserController"
                ],
                "summary": "添加用户信息",
                "operationId": "getSystemUserPageData",
                "parameters": [
                    {
                        "description": "获取用户页数据请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SystemUserPageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_PageResult-response_SystemUserPageVo"
                        }
                    }
                }
            }
        },
        "/user/remove": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemUserController"
                ],
                "summary": "删除用户信息",
                "operationId": "removeSystemUserInfo",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-bool"
                        }
                    }
                }
            }
        },
        "/user/reset_pwd": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemUserController"
                ],
                "summary": "重置用户密码",
                "operationId": "resetUserPassword",
                "parameters": [
                    {
                        "description": "重置密码参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ResetUserPwdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-bool"
                        }
                    }
                }
            }
        },
        "/user/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systemUserController"
                ],
                "summary": "更新用户信息",
                "operationId": "updateSystemUserInfo",
                "parameters": [
                    {
                        "description": "更新用户数据请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateSystemUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-bool"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.AddDomainRequest": {
            "type": "object",
            "required": [
                "domainName"
            ],
            "properties": {
                "domainName": {
                    "type": "string"
                }
            }
        },
        "request.AddSystemUserRequest": {
            "type": "object",
            "required": [
                "domainId",
                "isAdmin",
                "nickname",
                "password",
                "username"
            ],
            "properties": {
                "domainId": {
                    "description": "域id",
                    "type": "integer"
                },
                "isAdmin": {
                    "description": "是否为管理员",
                    "type": "boolean"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "request.DBConnectionRequest": {
            "type": "object",
            "required": [
                "dbType",
                "password",
                "username"
            ],
            "properties": {
                "dbType": {
                    "description": "数据库类型",
                    "type": "string"
                },
                "host": {
                    "description": "服务器地址",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "port": {
                    "description": "端口",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "request.InitProjectRequest": {
            "type": "object",
            "required": [
                "adminAccount",
                "adminPassword",
                "dbName",
                "dbType",
                "password",
                "username"
            ],
            "properties": {
                "adminAccount": {
                    "description": "管理员账号",
                    "type": "string"
                },
                "adminPassword": {
                    "description": "管理员密码",
                    "type": "string"
                },
                "dbName": {
                    "description": "数据库名",
                    "type": "string"
                },
                "dbType": {
                    "description": "数据库类型",
                    "type": "string"
                },
                "host": {
                    "description": "服务器地址",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "port": {
                    "description": "端口",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "request.PwdLogin": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "request.ResetUserPwdRequest": {
            "type": "object",
            "required": [
                "password",
                "userId"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "request.SystemDomainPageRequest": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页",
                    "type": "integer"
                },
                "domainName": {
                    "type": "string"
                },
                "pageSize": {
                    "description": "页数据量",
                    "type": "integer"
                }
            }
        },
        "request.SystemUserPageRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账户名称",
                    "type": "string"
                },
                "current": {
                    "description": "当前页",
                    "type": "integer"
                },
                "isAdmin": {
                    "description": "是否管理员",
                    "type": "boolean"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "pageSize": {
                    "description": "页数据量",
                    "type": "integer"
                },
                "status": {
                    "description": "账号状态",
                    "type": "integer"
                }
            }
        },
        "request.UpdateDomainRequest": {
            "type": "object",
            "required": [
                "domainId",
                "domainName"
            ],
            "properties": {
                "domainId": {
                    "type": "integer"
                },
                "domainName": {
                    "type": "string"
                }
            }
        },
        "request.UpdateSystemUserRequest": {
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "isAdmin": {
                    "type": "boolean"
                },
                "nickname": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "response.CheckResult": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "boolean"
                }
            }
        },
        "response.PageResult-response_SystemUserPageVo": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页条数",
                    "type": "integer"
                },
                "records": {
                    "description": "数据列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.SystemUserPageVo"
                    }
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "response.PageResult-schema_SystemDomain": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页条数",
                    "type": "integer"
                },
                "records": {
                    "description": "数据列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.SystemDomain"
                    }
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "response.Response-any": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "example": "成功"
                }
            }
        },
        "response.Response-array_schema_SystemDomain": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.SystemDomain"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "成功"
                }
            }
        },
        "response.Response-bool": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "boolean"
                },
                "msg": {
                    "type": "string",
                    "example": "成功"
                }
            }
        },
        "response.Response-response_CheckResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/response.CheckResult"
                },
                "msg": {
                    "type": "string",
                    "example": "成功"
                }
            }
        },
        "response.Response-response_PageResult-response_SystemUserPageVo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/response.PageResult-response_SystemUserPageVo"
                },
                "msg": {
                    "type": "string",
                    "example": "成功"
                }
            }
        },
        "response.Response-response_PageResult-schema_SystemDomain": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/response.PageResult-schema_SystemDomain"
                },
                "msg": {
                    "type": "string",
                    "example": "成功"
                }
            }
        },
        "response.Response-response_SystemUserVo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/response.SystemUserVo"
                },
                "msg": {
                    "type": "string",
                    "example": "成功"
                }
            }
        },
        "response.SystemUserPageVo": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间",
                    "type": "string"
                },
                "domainName": {
                    "description": "所属域",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "isAdmin": {
                    "description": "是否为管理员",
                    "type": "boolean"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "integer"
                },
                "userId": {
                    "description": "用户id",
                    "type": "integer"
                }
            }
        },
        "response.SystemUserVo": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "isAdmin": {
                    "description": "是否为管理员",
                    "type": "boolean"
                },
                "nickname": {
                    "description": "昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                },
                "userId": {
                    "description": "用户id",
                    "type": "integer"
                }
            }
        },
        "schema.SystemDomain": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "string"
                },
                "domainId": {
                    "type": "integer"
                },
                "domainName": {
                    "type": "string"
                },
                "isDelete": {
                    "type": "boolean"
                },
                "updateTime": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gin Swagger Demo API",
	Description:      "This is a sample server for Gin Swagger.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
